# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxButtonControl' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxButtonControl
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  

  target 'RxButtonControlTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxButtonControlUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
