# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleSelectableDate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SwiftDate'
  # Pods for SampleSelectableDate

  target 'SampleSelectableDateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleSelectableDateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
