# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SettingSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SettingSample
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'

  target 'SettingSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SettingSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
