# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleProtocol' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftDate'
  pod 'SwiftGen'

  # Pods for SampleProtocol

  target 'SampleProtocolTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleProtocolUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
